
#ifndef MAM_SENSOR_CLIENT_CONFIG_H
#define MAM_SENSOR_CLIENT_CONFIG_H

#define IOTA_HOST "node05.iotatoken.nl"
#define IOTA_PORT 16265
#define IOTA_SEED "RTYNARMDLBLMOWRFCEEFMJFFLCTAHWEBKSPJQGHMHCSQPVUI9NDZMJITSGAZOGRGHGZRKSPCPWAWTVPXA"


#define SOCKET_BUFFER_SIZE 1024
#define DEBUG_SERVER true
#define PORT 8085

#define MAM_ENCODE_BUFFER 2048

#define CLIENT_ADDRESS "fe80::1a:7dff:feda:7113"
#define SENSOR_ADDRESS "fe80::e0ca:46ff:fed3:1967"
#define INTERFACE_NAME "bt0"

#define SENSOR_NODES_LENGTH 1

#endif //MAM_SENSOR_CLIENT_CONFIG_H
